all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /home/ec2-user/Confluent.pem
    security_mode: tls
preflight:
  hosts:
    172.31.83.177:
    172.31.89.42:
    172.31.93.141:
    172.31.95.36:
zookeeper:
  hosts:
    172.31.83.177:
    172.31.89.42:
    172.31.93.141:
broker:
  hosts:
    172.31.83.177:
      kafka:
        broker:
          id: 1
    172.31.89.42:
      kafka:
        broker:
          id: 2
    172.31.93.141:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    172.31.95.36:
control-center:
  hosts:
    172.31.95.36:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 172.31.95.36:8083
connect-distributed:
  hosts:
    172.31.95.36:
kafka-rest:
  hosts:
    172.31.95.36:
ksql:
  hosts:
    172.31.95.36:
tools:
  hosts:
    172.31.83.177:
