all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: centos
    ansible_become: true
    security_mode: sasl_ssl
preflight:
  hosts:
    ip-172-31-24-74.us-east-2.compute.internal:
    ip-172-31-22-155.us-east-2.compute.internal:
    ip-172-31-27-4.us-east-2.compute.internal:
    ip-172-31-16-25.us-east-2.compute.internal:
    ip-172-31-29-22.us-east-2.compute.internal:
    ip-172-31-20-223.us-east-2.compute.internal:
    ip-172-31-31-195.us-east-2.compute.internal:
ssl_CA:
  hosts:
    ip-172-31-24-74.us-east-2.compute.internal:
zookeeper:
  hosts:
    ip-172-31-24-74.us-east-2.compute.internal:
    ip-172-31-22-155.us-east-2.compute.internal:
    ip-172-31-27-4.us-east-2.compute.internal:
broker:
  hosts:
    ip-172-31-24-74.us-east-2.compute.internal:
      kafka:
        broker:
          id: 1
    ip-172-31-22-155.us-east-2.compute.internal:
      kafka:
        broker:
          id: 2
    ip-172-31-27-4.us-east-2.compute.internal:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ip-172-31-16-25.us-east-2.compute.internal:
control-center:
  hosts:
    ip-172-31-29-22.us-east-2.compute.internal:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ip-172-31-20-223.us-east-2.compute.internal:8083
connect-distributed:
  hosts:
    ip-172-31-20-223.us-east-2.compute.internal:
kafka-rest:
  hosts:
    ip-172-31-20-223.us-east-2.compute.internal:
ksql:
  hosts:
    ip-172-31-31-195.us-east-2.compute.internal:
tools:
  hosts:
    ip-172-31-24-74.us-east-2.compute.internal:

