- name: Install Java
  yum:
    name: "java-1.8.0-openjdk"
    state: latest
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
- file:
    path: /var/private/ssl
    state: directory
    mode: 0755
- copy:
   src: sslcerts/kafka-server-truststore.jks
   dest: /var/private/ssl/kafka-server-truststore.jks
- copy:
   src: sslcerts/kafka-server-keystore.jks
   dest: /var/private/ssl/kafka-server-keystore.jks
- copy:
   src: sslcerts/kafka-client-truststore.jks
   dest: /var/private/ssl/kafka-client-truststore.jks
- copy:
   src: sslcerts/kafka-client-keystore.jks
   dest: /var/private/ssl/kafka-client-keystore.jks

